-- Copyright (C) 1991-2013 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- Generated by Quartus II Version 13.0.1 Build 232 06/12/2013 Service Pack 1 SJ Web Edition
-- Created on Thu Mar 12 16:59:14 2026

LIBRARY ieee;
USE ieee.std_logic_1164.all;

ENTITY paridad IS
    PORT (
        clock : IN STD_LOGIC;
        reset : IN STD_LOGIC := '0';
        DIGITO : IN STD_LOGIC := '0';
        PAR : OUT STD_LOGIC
    );
END paridad;

ARCHITECTURE BEHAVIOR OF paridad IS
    TYPE type_fstate IS (E_PAR,E_IMPAR);
    SIGNAL fstate : type_fstate;
    SIGNAL reg_fstate : type_fstate;
BEGIN
    PROCESS (clock,reg_fstate)
    BEGIN
        IF (clock='1' AND clock'event) THEN
            fstate <= reg_fstate;
        END IF;
    END PROCESS;

    PROCESS (fstate,reset,DIGITO)
    BEGIN
        IF (reset='1') THEN
            reg_fstate <= E_PAR;
            PAR <= '0';
        ELSE
            PAR <= '0';
            CASE fstate IS
                WHEN E_PAR =>
                    IF (NOT((DIGITO = '1'))) THEN
                        reg_fstate <= E_PAR;
                    ELSIF ((DIGITO = '1')) THEN
                        reg_fstate <= E_IMPAR;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= E_PAR;
                    END IF;

                    PAR <= '1';
                WHEN E_IMPAR =>
                    IF (NOT((DIGITO = '1'))) THEN
                        reg_fstate <= E_IMPAR;
                    ELSIF ((DIGITO = '1')) THEN
                        reg_fstate <= E_PAR;
                    -- Inserting 'else' block to prevent latch inference
                    ELSE
                        reg_fstate <= E_IMPAR;
                    END IF;

                    PAR <= '0';
                WHEN OTHERS => 
                    PAR <= 'X';
                    report "Reach undefined state";
            END CASE;
        END IF;
    END PROCESS;
END BEHAVIOR;
